Bee Project/Areas/Customer/Controllers/CustomerProfileController.cs
using Bee_Project.Areas.Customer.Models.VModel;
using Bee_Project.Areas.ServiceProvider.Models.VModel;
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;


namespace Bee_Project.Areas.Customer.Controllers
{
    public class CustomerProfileController : Controller
    {
        // GET: Customer/CustomerProfile
      
        private ApplicationDbContext _context;

        public CustomerProfileController()
        {
            _context = new ApplicationDbContext();
           
        }
      
       VMCustomer userVMB;
       [HttpGet]
       public ActionResult Profile()
       {
           string currentuserid = User.Identity.GetUserId();
           userVMB = new VMCustomer();
           Bee_Project.Models.Customer customerdb = _context.Customers.Where(m => m.UserID == currentuserid).First();
           userVMB.UserName = customerdb.UserName;
           userVMB.Phone = customerdb.PhoneNumber;

           userVMB.Addresses = new AddressesVM();
           userVMB.Addresses.Addresses = new Addresse();
           if (customerdb.AddressesID != 0)
           {
               userVMB.AddressesID = customerdb.AddressesID;
               userVMB.Addresses.Addresses = _context.Addresses.Where(m => m.ID == customerdb.AddressesID).First();
           }
           userVMB.Addresses.Countries = _context.Countrys.ToList();
           userVMB.Addresses.cities = _context.Cities.ToList();
           return View(userVMB);

       }
       [HttpPost]
       public ActionResult Save(VMCustomer uservmmode)
       {

           string currentuserid = User.Identity.GetUserId();
           Bee_Project.Models.Customer Customer = _context.Customers.Where(m => m.UserID == currentuserid).First();
           Customer.UserName = uservmmode.UserName;
           Customer.PhoneNumber = uservmmode.Phone;
           
           if (uservmmode.AddressesID == 0)
           {
               _context.Addresses.Add(uservmmode.Addresses.Addresses);
               _context.SaveChanges();

               uservmmode.AddressesID = uservmmode.Addresses.Addresses.ID;
               Customer.AddressesID = uservmmode.AddressesID;
           }
           Addresse addressesdb = _context.Addresses.Where(m => m.ID == uservmmode.AddressesID).First();
           addressesdb = uservmmode.Addresses.Addresses;

           _context.SaveChanges();

           return RedirectToAction("Profile");


       }


    }
}

Bee Project/Areas/Customer/Views/CustomerProfile/Profile.cshtml
@model Bee_Project.Areas.Customer.Models.VModel.VMCustomer

@{
    ViewBag.Title = "Profile";
Layout = "~/Areas/Customer/Views/Shared/_Layout.cshtml";
}

<h2>Profile</h2>


@using (Html.BeginForm("Save", "CustomerProfile"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Personal Inormation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div>
            @{Html.RenderPartial("~/Areas/Customer/Views/Shared/Addresses.cshtml", Model);}
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<div id="map"></div>
<div>
 
   
    @Html.ActionLink("Home Page", "Index", "Home", new { area = "" }, null)
</div>
<script src="~/Scripts/staticLocation.js"></script>

<script src="~/Scripts/mapsGUI.js"></script>
<script type="text/javascript">startMapPlugin('Addresses_Addresses_ultitude', 'Addresses_Addresses_longitude', true)</script>
<script type="text/javascript"> initMap()</script>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}