Bee Project/Areas/ServiceProvider/Models/ServiceAppointmentItem.cs
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bee_Project.Areas.ServiceProvider.Models
{
    public class ServiceAppointmentItem
    {
        public Bee_Project.Models.Customer user { set; get; }
        public string name{set;get;}
        public string phone { set; get; }
        public string email { set; get; }
         [DataType(DataType.Date)]
        public DateTime date{set;get;}

        public UserAppointment UAppointment { set; get; }

    }
}

Bee Project/Areas/ServiceProvider/Models/VModel/AddressesVM.cs
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bee_Project.Areas.ServiceProvider.Models.VModel
{
    public class AddressesVM
    {


        public Addresse Addresses { get; set; }
        public List<Country> Countries { get; set; }
        public List<City> cities { get; set; }
    }
}

Bee Project/Areas/ServiceProvider/Models/VModel/UserVM.cs
using Bee_Project.Models;
using Bee_Project.Areas.ServiceProvider.Models.VModel;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Bee_Project.Areas.ServiceProvider.Models.VMModel
{
    public class UserVM
    {

        [Required]
        [Key]
        public int UserID { get; set; }

        [Required]
        [StringLength(50)]
        public string UserName { get; set; }

        [Required]
        [StringLength(50)]
        public string CompanyName { get; set; }

        [DataType(DataType.PhoneNumber)]
        public string Phone { get; set; }

        [DataType(DataType.EmailAddress)]
        [Required]
        public string Email { get; set; }

        public int AddressesID { get; set; }
     
        public AddressesVM Addresses { get; set; }


    }
}

Bee Project/Areas/ServiceProvider/Models/VModel/VAppointment.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Bee_Project.Areas.ServiceProvider.Models.VModel
{
    public class VAppointment
    {
      
        public int ID { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime StartDate { get; set; }

        [Required]
        [DataType(DataType.Date)]
        public DateTime EndDate { get; set; }

        [Required]
        [DataType(DataType.Time)]
        public DateTime StartTime { get; set; }

        [Required]
        [DataType(DataType.Time)]
        public DateTime EndTime { get; set; }

        [Required]
        public bool IsAvailable { get; set; }

        [Required]
        public bool IsBooked { get; set; }

        [Required]
        public bool IsCancelled { get; set; }

        [Required]
        public bool IsPostponed { get; set; }

        public int UserID { get; set; }


        public int ServiceID { get; set; }

        public double Duration { get; set; }

        public Boolean Sat { get; set; }
        public Boolean Sun { get; set; }
        public Boolean Mon { get; set; }
        public Boolean Tue { get; set; }
        public Boolean Wed { get; set; }
        public Boolean Thu { get; set; }
        public Boolean Fri { get; set; }
        
    }
}

Bee Project/Areas/ServiceProvider/Models/VModel/VService.cs
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Bee_Project.Areas.ServiceProvider.Models.VModel
{
    public class VService
    {
        
        public int ID { set; get; }
        public string Name { set; get; }
        
        
        public string Ditrict { set; get; }
        public string Street { set; get; }
        public int FloorNumber { set; get; }
        public int DoorNumber { set; get; }
        public string Building { set; get; }
        public string PostalCode { set; get; }
        public string longitude { set; get; }
        public string altitude { set; get; }
 
        


        //additional

        public List<SelectListItem> ServiceTypes { set; get; }
        public IEnumerable<SelectListItem> Cities { set; get; }
        public int selectedCities { set; get; }
        public int selectedCountries { set; get; }
        public int  selectedServiceTypes { set; get; }
        public List<SelectListItem> Countries { set; get; }

        [DataType(DataType.MultilineText)]
        public string serviceInfo { get; set; }

        [DataType(DataType.MultilineText)]
        public string serviceMetaData { get; set; }
    }
}

Bee Project/Areas/ServiceProvider/Models/VModel/VServiceItem.cs
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Bee_Project.Areas.ServiceProvider.Models.VModel
{
    public class VServiceItem
    {
        public int ID { get; set; }
        public string serviceName { set; get; }
        public string ServiceType { set; get; }
        public string serviceMetaData { set; get; }
        public string serviceCity { get; set; }
        public string serviceCountry { get; set; }
     

        public string serviceDetails { get; set; }

        public  List<Appointment> appointments  { get; set; }


        


    }
}

Bee Project/Areas/ServiceProvider/Controllers/AppointmentController.cs
using Bee_Project.Areas.ServiceProvider.Models.VModel;
using Bee_Project.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.AspNet.Identity;
using System.Data.Entity;

namespace Bee_Project.Areas.ServiceProvider.Controllers
{
    public class AppointmentController : Controller
    {
        //
        private ApplicationDbContext dbContext;
        public AppointmentController() { dbContext = new ApplicationDbContext(); }

        // GET: /ServiceProvider/Appointment/
        [HttpGet]
        public ActionResult CreateAppointment()
        {
            try
            {
                int ServiceID = int.Parse(Url.RequestContext.RouteData.Values["id"].ToString());
                Appointment App = new Appointment();
                App.ServiceID = ServiceID;
                return View(App);
            }
            catch { return Redirect(Url.Content("~/ServiceProvider/Service/ListServices"));}
        }

        [HttpGet]
        public ActionResult EditAppointment()
        {
            int AppointmentID = int.Parse(Url.RequestContext.RouteData.Values["id"].ToString());
            Appointment app = dbContext.Appointments.Where(x => x.ID == AppointmentID).First();
            TempData["serviceID"]=app.ServiceID;
            return View(app);
        }

        [HttpPost]
        public ActionResult EditAppointment(Appointment app)
        {
            int serviceID =Int16.Parse(TempData["serviceID"].ToString());

            app.ServiceID = serviceID;
            dbContext.Entry(app).State = EntityState.Modified;
            dbContext.SaveChanges();
            List<UserAppointment> serviceUserAppintments = dbContext.UserAppointment.Where(x => x.AppointmentID == app.ID && x.UserID != null).ToList();

          dbContext.UserAppointment.RemoveRange( dbContext.UserAppointment.Where(x => x.AppointmentID == app.ID).ToList());

            for (var dt = app.StartDate; dt <= app.EndDate; dt = dt.AddDays(1))
            {
                switch (dt.DayOfWeek)
                {
                    case DayOfWeek.Saturday: if (!app.Sat) continue;
                        break;
                    case DayOfWeek.Sunday: if (!app.Sun) continue;
                        break;
                    case DayOfWeek.Monday: if (!app.Mon) continue;
                        break;
                    case DayOfWeek.Tuesday: if (!app.Tue) continue;
                        break;
                    case DayOfWeek.Wednesday: if (!app.Wed) continue;
                        break;
                    case DayOfWeek.Thursday: if (!app.Thu) continue;
                        break;
                    case DayOfWeek.Friday: if (!app.Fri) continue;
                        break;
                }

                DateTime startTime = app.StartTime;
                DateTime endTime = app.EndTime;

                for (var tm = startTime; tm <= endTime; tm.AddHours(app.Duration))
                {
                    UserAppointment Uapp = new UserAppointment();
                    Uapp.appointmentDate = dt;
                    Uapp.AppointmentID = app.ID;
                    Uapp.startTime = tm;
                    Uapp.endTime = tm.AddHours(app.Duration);
                    Uapp.canceled = false;
                    dbContext.UserAppointment.Add(Uapp);
                    if (serviceUserAppintments != null)
                    {
                        UserAppointment similarTime = serviceUserAppintments.Where(x => x.appointmentDate.Equals(Uapp.appointmentDate) && x.startTime.Equals(Uapp.startTime) && x.endTime.Equals(Uapp.endTime)).First();
                        if(similarTime != null)
                        {
                            Uapp.UserID = similarTime.UserID;
                            serviceUserAppintments.Remove(similarTime);
                        }
                     
                      
                    }
                    dbContext.SaveChanges();
                }
                // canceled for time change 
                foreach (UserAppointment ua in serviceUserAppintments)
                {
                    userAppointmentLog ual = new userAppointmentLog();
                    ual.canceled = true;
                    ual.date = ua.appointmentDate;
                    ual.startTime = ua.startTime;
                    ual.endTime = ua.endTime;
                    ual.ServiceID = app.ServiceID;
                    ual.userID = ua.UserID;
                    ual.duration = app.Duration;
                    dbContext.userAppointmentLog.Add(ual);
                }
                dbContext.SaveChanges();
            }
            return Redirect(Url.Content("~/ServiceProvider/Appointment/ListAppointments/" + app.ServiceID));
        }

        public ActionResult deleteAppointment()
        {
            int appointmentID = int.Parse(Url.RequestContext.RouteData.Values["id"].ToString());
            
            Appointment app = dbContext.Appointments.Where(x => x.ID == appointmentID).First();
            int ServiceID = app.ServiceID;

            //cancel users appointments

            List<UserAppointment> serviceUserAppintments = dbContext.UserAppointment.Where(x => x.AppointmentID == app.ID && x.UserID != null).ToList();
            foreach (UserAppointment ua in serviceUserAppintments)
            {
                userAppointmentLog ual = new userAppointmentLog();
                ual.canceled = true;
                ual.date = ua.appointmentDate;
                ual.startTime = ua.startTime;
                ual.endTime = ua.endTime;
                ual.ServiceID = app.ServiceID;
                ual.userID = ua.UserID;
                ual.duration = app.Duration;
                dbContext.userAppointmentLog.Add(ual);
                dbContext.UserAppointment.Remove(ua);
            }
            dbContext.SaveChanges();



            dbContext.Appointments.Remove(app);
            dbContext.SaveChanges();
            return Redirect(Url.Content("~/ServiceProvider/Appointment/ListAppointments/" + ServiceID));

        }

        [HttpPost]
        public ActionResult CreateAppointment(Appointment App)
        {
            int ServiceID = int.Parse(Url.RequestContext.RouteData.Values["id"].ToString());
            App.ServiceID = ServiceID;
            dbContext.Appointments.Add(App);
            dbContext.SaveChanges();

            for (var dt = App.StartDate; dt <= App.EndDate; dt = dt.AddDays(1))
            {
                switch(dt.DayOfWeek) {
                    case DayOfWeek.Saturday: if (!App.Sat) continue;
                        break;
                    case DayOfWeek.Sunday: if (!App.Sun) continue;
                        break;
                    case DayOfWeek.Monday: if (!App.Mon) continue;
                        break;
                    case DayOfWeek.Tuesday: if (!App.Tue) continue;
                        break;
                    case DayOfWeek.Wednesday: if (!App.Wed) continue;
                        break;
                    case DayOfWeek.Thursday: if (!App.Thu) continue;
                        break;
                    case DayOfWeek.Friday: if (!App.Fri) continue;
                        break;
                    }

                DateTime startTime = App.StartTime;
                DateTime endTime = App.EndTime;
                var tm = startTime;
                while (TimeSpan.Compare(tm.TimeOfDay, endTime.TimeOfDay) <= 0)
                {
                    UserAppointment UAPP = new UserAppointment();
                    UAPP.appointmentDate = dt;
                    UAPP.AppointmentID = App.ID;
                    UAPP.startTime = tm;
                    UAPP.endTime = tm.AddHours(App.Duration);
                    UAPP.canceled = false;
                    dbContext.UserAppointment.Add(UAPP);
                 
                    dbContext.SaveChanges();
                    tm = tm.AddHours(App.Duration);
                }
            } 
           
            return Redirect(Url.Content("~/ServiceProvider/Appointment/ListAppointments/"+App.ServiceID));

        }
       
        public ActionResult ListAppointments()
        {
            try
            {
                int ServiceID = int.Parse(Url.RequestContext.RouteData.Values["id"].ToString());
                List<Appointment> appointments = dbContext.Appointments.Where(x => x.ServiceID == ServiceID).ToList();
                TempData["ID"] = ServiceID;
                return View(appointments);
            }
            catch (Exception ex) { return Redirect(Url.Content("~/ServiceProvider/Service/ListServices")); }
              
        }
	}
}

Bee Project/Areas/ServiceProvider/Controllers/ServiceProviderController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Bee_Project.Areas.ServiceProvider.Models.VMModel;
using Bee_Project.Models;
using Microsoft.AspNet.Identity;

namespace Bee_Project.Areas.ServiceProvider.Controllers
{
    public class ServiceProviderController : Controller
    {
        // GET: ServiceProvider/ServiceProvider

        private ApplicationDbContext _context;

        public ServiceProviderController()
        {
            _context = new ApplicationDbContext();
        }
       
        UserVM userVMB;
        [HttpGet]
        public ActionResult Profile()
        {
            
            string currentuserid = User.Identity.GetUserId();
            userVMB = new UserVM();
            Bee_Project.Models.ServiceProvider userfromdb = _context.ServicesProviders.Where(m => m.UserID == currentuserid).First();
           userVMB.UserName = userfromdb.UserName;
           userVMB.Phone = userfromdb.PhoneNumber;
           userVMB.CompanyName = userfromdb.CompanyName;
           userVMB.Addresses = new Models.VModel.AddressesVM();
           userVMB.Addresses.Addresses = new Addresse();
           if (userfromdb.AddressesID!=0)
           {
               userVMB.AddressesID = userfromdb.AddressesID;
               userVMB.Addresses.Addresses = _context.Addresses.Where(m => m.ID == userfromdb.AddressesID).First();
           }
           userVMB.Addresses.Countries = _context.Countrys.ToList();
           userVMB.Addresses.cities = _context.Cities.ToList();
            return View(userVMB);
            
        }
        [HttpPost]
        public ActionResult Save(UserVM uservmmode)
        {
         
             string currentuserid = User.Identity.GetUserId();
              Bee_Project.Models.ServiceProvider serviceprovider = _context.ServicesProviders.Where(m => m.UserID == currentuserid).First();
              serviceprovider.UserName = uservmmode.UserName;
              serviceprovider.PhoneNumber = uservmmode.Phone;
              serviceprovider.CompanyName = uservmmode.CompanyName;
              if (uservmmode.AddressesID==0)
              { 
              _context.Addresses.Add(uservmmode.Addresses.Addresses);
              _context.SaveChanges();

              uservmmode.AddressesID=uservmmode.Addresses.Addresses.ID;
              serviceprovider.AddressesID = uservmmode.AddressesID;
              }
              Addresse addressesdb = _context.Addresses.Where(m => m.ID == uservmmode.AddressesID).First();
              addressesdb = uservmmode.Addresses.Addresses;

              _context.SaveChanges();

              return RedirectToAction("Profile");
            

        }
        public ActionResult CompanyProfile()
        {

            return View();
        }
        public ActionResult Service()
        {
            return View();
        }

        public ActionResult ServiceDetails()
        {
            return View();
        }

        


        [HttpPost]
        public ActionResult GetCityByStaeId(int stateid)
        {
          List< City>Cities = _context.Cities.Where(m => m.CountryID == stateid).ToList();

          SelectList obgcity = new SelectList(Cities, "Id", "CityName", 0);
          return Json(obgcity);
        }
    }


}

Bee Project/Areas/ServiceProvider/Views/ServiceProvider/Addresses.cshtml
@model Bee_Project.Areas.ServiceProvider.Models.VMModel.UserVM


<div class="form-horizontal">
    <h4>Addresse</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Addresses.Addresses.ID)

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.CountryID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">


            @Html.DropDownListFor(model => model.Addresses.Addresses.CountryID, new SelectList(Model.Addresses.Countries, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.CountryID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.CityID, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownListFor(model => model.Addresses.Addresses.CityID, new SelectList(Model.Addresses.cities, "Id", "Name"), new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.CityID, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.Ditricit, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.Ditricit, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.Ditricit, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.Street, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.Street, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.Street, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.Building, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.Building, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.Building, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.Floornumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.Floornumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.Floornumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.DoorNumber, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.DoorNumber, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.DoorNumber, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.PotalCode, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.PotalCode, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.PotalCode, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.longitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.longitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.longitude, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Addresses.Addresses.ultitude, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Addresses.Addresses.ultitude, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Addresses.Addresses.ultitude, "", new { @class = "text-danger" })
        </div>
    </div>


</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bee Project/Areas/ServiceProvider/Views/ServiceProvider/Profile.cshtml
@model Bee_Project.Areas.ServiceProvider.Models.VMModel.UserVM

@{
    ViewBag.Title = "Profile";
    Layout = "~/Areas/ServiceProvider/Views/Shared/_Layout.cshtml";
}



<h2>Profile</h2>


@using (Html.BeginForm("Save","ServiceProvider"))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Personal Inormation</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.UserID)

        <div class="form-group">
            @Html.LabelFor(model => model.UserName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.UserName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.UserName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.CompanyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CompanyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
            </div>
        </div>
       
        <div>
            @{Html.RenderPartial("~/Areas/ServiceProvider/Views/ServiceProvider/Addresses.cshtml", Model);}
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Home Page", "Index", "Home", new { area = "" }, null)
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Bee Project/Areas/ServiceProvider/Views/ServiceProvider/Service.cshtml
@{
    ViewBag.Title = "Service";
}

<h2>Service</h2>

Bee Project/Areas/ServiceProvider/Views/ServiceProvider/ServiceDetails.cshtml
@{
    ViewBag.Title = "ServiceDetails";
}

<h2>ServiceDetails</h2>